/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesRouteRouteImport } from './routes/_pages/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesOurstoryRouteImport } from './routes/_pages/ourstory'
import { Route as PagesCliniciansIndexRouteImport } from './routes/_pages/clinicians/index'
import { Route as PagesCliniciansLyndseyRouteImport } from './routes/_pages/clinicians/lyndsey'

const PagesRouteRoute = PagesRouteRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesOurstoryRoute = PagesOurstoryRouteImport.update({
  id: '/ourstory',
  path: '/ourstory',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesCliniciansIndexRoute = PagesCliniciansIndexRouteImport.update({
  id: '/clinicians/',
  path: '/clinicians/',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesCliniciansLyndseyRoute = PagesCliniciansLyndseyRouteImport.update({
  id: '/clinicians/lyndsey',
  path: '/clinicians/lyndsey',
  getParentRoute: () => PagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ourstory': typeof PagesOurstoryRoute
  '/clinicians/lyndsey': typeof PagesCliniciansLyndseyRoute
  '/clinicians/': typeof PagesCliniciansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ourstory': typeof PagesOurstoryRoute
  '/clinicians/lyndsey': typeof PagesCliniciansLyndseyRoute
  '/clinicians': typeof PagesCliniciansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages': typeof PagesRouteRouteWithChildren
  '/_pages/ourstory': typeof PagesOurstoryRoute
  '/_pages/clinicians/lyndsey': typeof PagesCliniciansLyndseyRoute
  '/_pages/clinicians/': typeof PagesCliniciansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ourstory' | '/clinicians/lyndsey' | '/clinicians/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ourstory' | '/clinicians/lyndsey' | '/clinicians'
  id:
    | '__root__'
    | '/'
    | '/_pages'
    | '/_pages/ourstory'
    | '/_pages/clinicians/lyndsey'
    | '/_pages/clinicians/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRouteRoute: typeof PagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/ourstory': {
      id: '/_pages/ourstory'
      path: '/ourstory'
      fullPath: '/ourstory'
      preLoaderRoute: typeof PagesOurstoryRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/clinicians/': {
      id: '/_pages/clinicians/'
      path: '/clinicians'
      fullPath: '/clinicians/'
      preLoaderRoute: typeof PagesCliniciansIndexRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/clinicians/lyndsey': {
      id: '/_pages/clinicians/lyndsey'
      path: '/clinicians/lyndsey'
      fullPath: '/clinicians/lyndsey'
      preLoaderRoute: typeof PagesCliniciansLyndseyRouteImport
      parentRoute: typeof PagesRouteRoute
    }
  }
}

interface PagesRouteRouteChildren {
  PagesOurstoryRoute: typeof PagesOurstoryRoute
  PagesCliniciansLyndseyRoute: typeof PagesCliniciansLyndseyRoute
  PagesCliniciansIndexRoute: typeof PagesCliniciansIndexRoute
}

const PagesRouteRouteChildren: PagesRouteRouteChildren = {
  PagesOurstoryRoute: PagesOurstoryRoute,
  PagesCliniciansLyndseyRoute: PagesCliniciansLyndseyRoute,
  PagesCliniciansIndexRoute: PagesCliniciansIndexRoute,
}

const PagesRouteRouteWithChildren = PagesRouteRoute._addFileChildren(
  PagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRouteRoute: PagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
