/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesRouteRouteImport } from './routes/_pages/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesOurstoryRouteImport } from './routes/_pages/ourstory'
import { Route as PagesCliniciansRouteImport } from './routes/_pages/clinicians'

const PagesRouteRoute = PagesRouteRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesOurstoryRoute = PagesOurstoryRouteImport.update({
  id: '/ourstory',
  path: '/ourstory',
  getParentRoute: () => PagesRouteRoute,
} as any)
const PagesCliniciansRoute = PagesCliniciansRouteImport.update({
  id: '/clinicians',
  path: '/clinicians',
  getParentRoute: () => PagesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinicians': typeof PagesCliniciansRoute
  '/ourstory': typeof PagesOurstoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinicians': typeof PagesCliniciansRoute
  '/ourstory': typeof PagesOurstoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pages': typeof PagesRouteRouteWithChildren
  '/_pages/clinicians': typeof PagesCliniciansRoute
  '/_pages/ourstory': typeof PagesOurstoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinicians' | '/ourstory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinicians' | '/ourstory'
  id: '__root__' | '/' | '/_pages' | '/_pages/clinicians' | '/_pages/ourstory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesRouteRoute: typeof PagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/ourstory': {
      id: '/_pages/ourstory'
      path: '/ourstory'
      fullPath: '/ourstory'
      preLoaderRoute: typeof PagesOurstoryRouteImport
      parentRoute: typeof PagesRouteRoute
    }
    '/_pages/clinicians': {
      id: '/_pages/clinicians'
      path: '/clinicians'
      fullPath: '/clinicians'
      preLoaderRoute: typeof PagesCliniciansRouteImport
      parentRoute: typeof PagesRouteRoute
    }
  }
}

interface PagesRouteRouteChildren {
  PagesCliniciansRoute: typeof PagesCliniciansRoute
  PagesOurstoryRoute: typeof PagesOurstoryRoute
}

const PagesRouteRouteChildren: PagesRouteRouteChildren = {
  PagesCliniciansRoute: PagesCliniciansRoute,
  PagesOurstoryRoute: PagesOurstoryRoute,
}

const PagesRouteRouteWithChildren = PagesRouteRoute._addFileChildren(
  PagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesRouteRoute: PagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
